piwigo-nginx:
  build: .
  dockerfile: Dockerfile.nginx
  container_name: piwigo-nginx
  ports:
    - "8081:80"
  volumes_from:
    - piwigo-fpm

piwigo-fpm:
  build: .
  dockerfile: Dockerfile.fpm
  container_name: piwigo-fpm
  volumes_from:
    - piwigo-data
  volumes:
    - /srv/piwigo/galleries:/var/www/piwigo/galleries
    - /srv/piwigo/upload:/var/www/piwigo/upload

piwigo-data:
  build: .
  dockerfile: Dockerfile.piwigo
  container_name: piwigo-data
