version: "3"
services:
  piwigo:
    build: .
    network_mode: bridge
    ports:
      - "8000:8000"
    links:
      - mysql

  mysql:
    image: mysql:5
    network_mode: bridge
    environment:
      MYSQL_USER: "piwigo"
      MYSQL_PASSWORD: "piwigo"
      MYSQL_DATABASE: "piwigo"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
